training:
  batch_size: 64
  epochs: 1000
  early_stop: 50
  learning_rate: 0.001
  optimizer:
    type: rmsprop

input_features:
  - name: project_type
    type: category

  - name: project_owner
    type: category

  - name: base_price
    type: numerical
    preprocessing:
      missing_value_strategy: fill_with_mean
      normalization: zscore

  # - name: target_price
  #   type: numerical
  # preprocessing:
  #   missing_value_strategy: fill_with_mean
  #   normalization: zscore
  - name: bid_days
    type: numerical

  - name: bid_start_month
    type: category

  - name: bid_start_weekday
    type: category

  # - name: bid_start_quarter
  #   type: category
  # - name: max_target_rate
  #   type: numerical
  # - name: min_target_rate
  #   type: numerical
  # - name: mean_target_rate
  #   type: numerical
  # - name: std_target_rate
  #   type: numerical
  # - name: count_bidding
  #   type: numerical

output_features:
  - name: target_rate
    type: numerical
    optimizer:
      type: loss
    # num_fc_layers: 4
    # fc_size: 1024
    # optimizer:
    #   type: loss
    # num_fc_layers: 4
    # fc_size: 128
    fc_layers:
      [{ fc_size: 512 }, { fc_size: 256 }, { fc_size: 128 }, { fc_size: 64 }]
    # clip: [98, 102]
